sequenceDiagram
  participant remote as UW-POLS501/student
  participant local as local repository
  remote->>local: Clone repository
  Note over remote: Assignment 1
  loop Until completed
    local->>local: Work and commit
    local->>remote: Push changes
  end
  remote->>remote: Open issue to submit
  Note over remote: Assignment 2
  loop Until completed
    local->>local: Work and commit
    local->>remote: Push changes
  end
  remote->>remote: Open issue to submit
