---
title: Assignments
---

## Overview

Assignments will be distributed and submitted using GitHub.

Each assignment will have three steps:

1.  Initial submission
1.  Peer review (1 week after initial submission)
1.  Corrections (1 week after peer review)

There will be approximately 4--6 assignments.

### Initial Submission

Submissions of all assignments should include both an R Markdown file and a compiled PDF file. Each assignment should be forked from the assignment repository, and submitted with a pull request. More detailed instructions are [here](https://github.com/UW-CSSS-564/assignment-2018-0).

The initial submission will be graded on the following 4-category scale:

| 4  | exceptional, above and beyond what was expected        |
| 3  | effort made to complete all questions; mostly correct  |
| 2  | some effort made for most or all questions             |
| 1  | submitted, but largely incomplete                      |
| 0  | did not submit                                         |

## Peer Review

After the solutions to each assignment is released, each student will be assigned to review two assignments.

### Instructions

These reviews will be submitted as comments on the pull request.
The comments should address the solution, code, and presentation:

-   Solutions:

    -   The reviewer should check whether the solutions are correct. A key will be provided.
    -   The reviewer should note incorrect or incomplete solutions, along with a suggestion of what they can do to fix it. The reviewer does not need to fix the problems, but they should provide indications of where the solution
    -   Note correct solutions.
    -   If you are unsure about a solution, note it clearly, and ask the instructors for assistance, or the author for clarification.

-   Code:

    -   Check that the code runs/compiles; in this class that means "does it knit?". It should run without editing, and produce the results
      presented.

    -   If any errors are encountered: include the exact error message as a code block in comments.

    -   The code should be clearly written, formatted, and easy to follow.

    -   There should not be errors or warnings in the code.

-   Presentation:

    -   Is the document clearly written, well formatted, such that you as a reviewer can follow and understand the solutions?

### Evaluation

Each peer review will be deemed “good” or “needs more”.[^peer-review]
Each review you do will give you 1 point if is "good" and 0 points if it "needs more".
Those will be totaled over all assignments to form your peer review mark.

How to give good comments:

-   Address questions that were answered incorrectly, unclearly, or particularly well.
-   Give thoughtful, constructive and considerate comments.
-   Be specific and concise.
-   Try to learn something new and, if you succeed, point that out.
-   If you can’t find anything to praise or that you found helpful, then at least offer some suggestions in a kind way.

Features of "needs more":

-   You do not address each question.
-   Your review is mean.
-   You can’t find anything to praise/learn and yet you don’t offer any suggestions either.

## Corrections

After receiving the key students will correct any issues with their
assignments. Corrections will be evaluated as follows:

| 1  | Acceptable   |
| 0  | Unacceptable |

[^peer-review]: Much of the section on suggestions for peer grading is derived from [Stat 545 Peer Review Guidelines](http://stat545.com/peer-review02_peer-evaluation-guidelines.html), licensed under the [CC BY-NC 3.0](https://creativecommons.org/licenses/by-nc/3.0/)
