# Chapter 6

Probability != Statistics. Probability is the mathematics of


For a good overview of the history of probability see ; for
a history of statistics.

See McElreath or Kruschke for feasible intro's to Bayesian stats.

Bayes probability vs. frequentist probability != inference.

In practice researchers will use some combination of these approaches.
Even frequentist inference is a mix between approaches of Neyman-Pearson and those of Fisher.
There are also reasons to think that the process of science is Bayesian even
if it may make sense to use frequentist estimators to answer particular problems.

On Monte Carlo simulation and computation in the history of statistics

Bayes rule != bayesian inferernce
 
Predicting race with surname:

- Federalist paper example
- Gender from name
- Age from name


Random variable is neither random nor a variable. It is a function from the
experiment (sample space) to a numeric value. These events are *mutually exclusive and exhaustive*.

- Discrete
- Continuous

Many similarities, but the underlying mathematics is different.
Important to know because of how

Note: these are abstractions. There are no such things are discrete or continous variables (at least in the processes we are talking about).
When representing a measurement as a random variable you are approxomating it.
many values = continuous. in some sense everything is discrete.
Discrete tends to be harder / more computational, so continuous distributions is useful.
The importance of this assumption or approximation will depend on the question and data you are using.

Link to probability distributions map, wikipedia.

What's important about probability distributions?

- continuous vs. discrete - what sort or random variable do we have?
- support - what values can it take?
- parameters - what are the knobs that we can adjust? What do they do?
- why is it being used? Flexible? Easy or hard to compute? Easy to compute would
    mean that there is are formula means, medians, common stats, and even some
    shortcuts for common cases. Things like if two random variables of this
    distribution are added together it is a random variable with these parameters.

Chapter in SMSS?

Summation vs. integration

Example from modern gameshow

Normal distribution

- Not all data is normal
- Central limit theorem -> normal
- Deep reason for normal distribution mean / standard deviation = max uncertianty

Meaning in R functions of r, p, q, d.

Rules of thumb for normal distribution

Sample mean and variance not equal to distribution mean and variance, but similar.

Sampling variability vs. other sources of uncertainy in polls. Freq or Bayesian?

History of the normal distribution ...

Sources for more on probability; books, cards


# Questions

- What is the definition of probability? What is Bayesian statistics?
    What is Frequentist statistics? How do their axioms differ?
- What was the probability that Democrats gain a majority in the Senate in the 2018 midterm election?
- Take an example and state what the *experiment*, *sample space*, and *events* are?
- What are the three probability axioms? Apply them to solve abstract problems.
- **Addition rule**
- **Law of total probability**
- Calculate permutation, calculate combination. What is the difference?
- Birthday problem?
- Work thorough the Schwartzenage message
- What is conditional probability?
- Monte Hall problem example?
- What is the density at a point?
- About how much probability mass is within +/- 1 sd, 2 sd, 3 sd in a normal distribution?
- What is the distribution of normal after adding value? multiplying?
- Expectation: as mean:  ? Variance: to ?
- Law of Large Numbers vs. Central Limit Theorem

Notation

- !
- n choose k

Vocab

- permutation
- combination
- Monte Carlo simulation
- sampling with and without replacement
- Birthday problem
- conditional probability
- independent
- marginal, joint
- Monte Hall problem
- Bayes's rule
- random variable
- continuous vs. discrete random variables
- probability mass function
- normal distribution
- Bernoulli distribution
- uniform distribution
- Binomial distribution
- Binomial theorem
- z-score
- expectation and variance
- law of large numbers
- central limit theorem?
