---
title: "Onboarding Instructions for CS&SS 564, Spring 2018"
---

Please complete the following before the first day of class (Tuesday, March 27, 2018).

1.  Sign up for our Slack worplace, <https://uwcsss564.slack.com>. We will use this for announcments, and asking and answering questions in this course. You should have received an invite. If not email the [instructors](cgilroy@uw.edu) to receive one.

2.  Sign into the course Slack workplace <https://uwcsss564.slack.com>, and leave a message on the [#onboarding](https://uwcsss564.slack.com/messages/C9TRYPV19/) channel.
    In the message introduce yourself, explain why you are taking this course, and what you hope to get out of taking this course.

2.  Tell use about yourself: Complete the pre-course survey. If you are registered for the course, you should have received an email. kIf not, you can find a link pinned on the `#onboarding` channel of Slack.

2.  We will use [git](https://git-scm.com/) for version control. and [GitHub](https://github.com/) for distributing, collecting, and commenting on assignments. 

    1.  Download [Git](https://git-scm.com/downloads) and install git.
        You should be able to use defaults for all settings.
    2.  Sign up for a GitHub account at <https://github.com> (if you do no already have one).
    3.  Tell us what your GitHub username is using the form emailed to you,
        or that can be found pinned on the `#onboarding` channel in Slack.
        
    
4.  Download that you have installed and downloaded R:

    1.  If you have R installed already, check have the latest version of R. 
        At the start of this course, the most recent version of R is **3.4.4**. 
        You can find this in R:
        
        ```rconsole
        $ sessionInf()
        ```
        
    2.  If you do not have R or the latest version of it installed, then download
        it from [CRAN](https://cloud.r-project.org/).
        
    3.  Update all installed R packages,
    
        ```rconsole
        $ update.packages(ask = FALSE)
        ```

5.  Download that install RStudio Desktop (Open Source Edition). RStudio provides a
    friendly interface to R (an IDE). (If you are proficient with R and have
    been using another IDE or text editor with R, you can skip this step.)

    1.  If you do not have RStudio installed, download and install it from [here](https://www.rstudio.com/products/rstudio/download/#download).
    
    2.  If you already have RStudio installed, check that you have the latest version
        by selecting `Help > Check for Updates` in the menu. Download and install
        the newest version if not.
        
6.  Install LaTeX. We will not use LaTeX directly. But we will use it to create PDFs from R Markdown files. If you do not have LaTeX installed on your machine, download and install a LaTeX distribution. There are many different distributions, but these are the ones common to each distribution.

    -   Windows: [MikTex](http://miktex.org/download)
    -   MacOS: [MacTex](https://tug.org/mactex/)
    -   Linux: `tex-live` is the most common LaTeX distribution. Install it
        using your distribution's package manager.

    Note, these are very large files and can take a while to download.

